repo:  https://github.com/openwrt/openwrt.git
branch: openwrt-21.02
revision: 378769b5551714ccaa821b481bfeecbf362f351e
output_dir: ./output

patch_folders:
  - patches/backports/
  - patches/ath79
  - patches/base
  - patches/ramips
  - patches/ipq40xx
  - patches/ipq806x
  - patches/ipq807x
  - patches/wifi
  - patches/rest
