name: Test Build Pull Request

on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linksys_e8450-ubi

    steps:
    - uses: actions/checkout@v2

    - name: Build image for ${{ matrix.target }}
      id: build
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        make -j TARGET=${{ matrix.target }}

    - name: Upload artifacts
      if:  always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}-artifacts
        path: openwrt/bin/

